# Generated by Django 4.2.6 on 2024-05-14 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AddField(
            model_name='sleepdata',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AddField(
            model_name='dailystep',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AddField(
            model_name='compliment',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_compliments', to='users.employee'),
        ),
        migrations.AddField(
            model_name='compliment',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_compliments', to='users.employee'),
        ),
        migrations.AddField(
            model_name='badge',
            name='employees',
            field=models.ManyToManyField(related_name='badges', to='users.employee'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='Goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.goal'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
    ]
