<<<<<<< HEAD
# Generated by Django 4.2.6 on 2024-05-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer_options', models.JSONField()),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='question')),
                ('category', models.CharField(choices=[('Dominance', 'D'), ('Influence', 'I'), ('Steadiness', 'S'), ('Conscientiousness', 'C')], default='Category', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('questions', models.ManyToManyField(to='quizzes.multiplechoicequestions')),
            ],
        ),
    ]
=======
# Generated by Django 4.2.6 on 2024-05-14 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer_options', models.JSONField()),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='question')),
                ('category', models.CharField(choices=[('Dominance', 'D'), ('Influence', 'I'), ('Steadiness', 'S'), ('Conscientiousness', 'C')], default='Category', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('questions', models.ManyToManyField(to='quizzes.multiplechoicequestions')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
            ],
        ),
    ]
>>>>>>> 99a36f899a430cba4556241f788f2c7f4c089439
